package com.example.firstapi.models.enums

import com.example.firstapi.util.Common.Companion.MER

enum class MerchantsLogosch(
    val id: Int,
    val merchantsNameEn: String,
    val merchantsNameAr: String,
    val logoUrl: String,
    val categories:MerchantCategories
) {
    MERCHANT_1(1 , "M.SOU" , "إم-سو" , "${MER}SOU.PNG",MerchantCategories.MERCHANT_CATEGORIES_1),
    MERCHANT_2(2 , "LC Waikiki" , "إل سي وايكيكي","",MerchantCategories.MERCHANT_CATEGORIES_1),
    MERCHANT_3(3 , "adidas kids" , "أديداس كيدز","",MerchantCategories.MERCHANT_CATEGORIES_1),
    MERCHANT_4(4 , "pixi" , "","بيكسي",MerchantCategories.MERCHANT_CATEGORIES_1),
    MERCHANT_5(5 , "NIKE" , "","نايك",MerchantCategories.MERCHANT_CATEGORIES_1),
    MERCHANT_6(6 , "Calvin Klein" , "كالفن كلاين","",MerchantCategories.MERCHANT_CATEGORIES_1),
    MERCHANT_7(7 , "Charles & Keith" , "تشارلز و كيث","",MerchantCategories.MERCHANT_CATEGORIES_1),
    MERCHANT_8(8 , "Polo Ralph Lauren" , "بولو - رالف لورين","",MerchantCategories.MERCHANT_CATEGORIES_1),
    MERCHANT_9(9 , "Hackett" , "هاكيت","",MerchantCategories.MERCHANT_CATEGORIES_1),
    MERCHANT_10(10 , "Tommy Hilfiger" , "تومي هيلفيجر","",MerchantCategories.MERCHANT_CATEGORIES_1),
    MERCHANT_11(11 , "Matalan" , "ماتالان","",MerchantCategories.MERCHANT_CATEGORIES_1),
    MERCHANT_12(12 , "Ofive" , "أو قايف","",MerchantCategories.MERCHANT_CATEGORIES_1),
    MERCHANT_13(13 , "New Balance" , "نيو بالانس","",MerchantCategories.MERCHANT_CATEGORIES_1),
    MERCHANT_14(14 , "Dejavu" , "ديجافو","",MerchantCategories.MERCHANT_CATEGORIES_1),
    MERCHANT_15(15 , "New Born" , "نيوبورن","",MerchantCategories.MERCHANT_CATEGORIES_1),
    MERCHANT_16(16 , "Town Team" , "تاون تيم","",MerchantCategories.MERCHANT_CATEGORIES_1),
    MERCHANT_17(17 , "Abou Shakra" , "ابو شقرة","",MerchantCategories.MERCHANT_CATEGORIES_2),
    MERCHANT_18(18 , "Kazouza" , "كازوزه","",MerchantCategories.MERCHANT_CATEGORIES_2),
    MERCHANT_19(19 , "Hajj Arafa" , "الحاج عرفة","",MerchantCategories.MERCHANT_CATEGORIES_2),
    MERCHANT_20(20 , "TBS" , "تي بي اس","",MerchantCategories.MERCHANT_CATEGORIES_2),
    MERCHANT_21(21 , "Carinos pizzeria" , "بيتزا كارينوس","",MerchantCategories.MERCHANT_CATEGORIES_2),
    MERCHANT_22(22 , "Chili's" , "تشيليز","",MerchantCategories.MERCHANT_CATEGORIES_2),
    MERCHANT_23(23 , "Kababgy Studio Masr" , "كبابجى ستوديو مصر","",MerchantCategories.MERCHANT_CATEGORIES_2),
    MERCHANT_24(24 , "La Poire" , "لابوار","",MerchantCategories.MERCHANT_CATEGORIES_2),
    MERCHANT_25(25 , "Beanos" , "بينوس","",MerchantCategories.MERCHANT_CATEGORIES_2),
    MERCHANT_26(26 , "Halaket El Samak" , "حلقة السمك","",MerchantCategories.MERCHANT_CATEGORIES_2),
    MERCHANT_27(27 , "La Poire café" , "مقهى لابوار","",MerchantCategories.MERCHANT_CATEGORIES_2),
    MERCHANT_28(28 , "Mama's" , " مطعم ماما","",MerchantCategories.MERCHANT_CATEGORIES_2),
    MERCHANT_29(29 , "Feteera" , "فطيرة","",MerchantCategories.MERCHANT_CATEGORIES_2),
    MERCHANT_30(30 , "Coppermelt" , "كوبرميلت","",MerchantCategories.MERCHANT_CATEGORIES_2),
    MERCHANT_31(31 , "Vinny's" , "فيني","",MerchantCategories.MERCHANT_CATEGORIES_2),
    MERCHANT_32(32 , "Monginis" , "مونجيني","",MerchantCategories.MERCHANT_CATEGORIES_2),
    MERCHANT_33(33 , "Vapiano" , "فابيانو","",MerchantCategories.MERCHANT_CATEGORIES_2),
    MERCHANT_34(34 , "Tradeline" , "تريدلاين","",MerchantCategories.MERCHANT_CATEGORIES_3),
    MERCHANT_35(35 , "CompuMe" , "كمبيومي","",MerchantCategories.MERCHANT_CATEGORIES_3),
    MERCHANT_36(36 , "Virgin Megastore" , "فيرجن ميجاستور","",MerchantCategories.MERCHANT_CATEGORIES_3),
    MERCHANT_37(37 , "RadioShack" , "راديو شاك","",MerchantCategories.MERCHANT_CATEGORIES_3),
    MERCHANT_38(38 , "Switch Plus" , "سويتش بلس","",MerchantCategories.MERCHANT_CATEGORIES_3),
    MERCHANT_39(39 , "Computer Shop" , "كمبيوتر شوب","",MerchantCategories.MERCHANT_CATEGORIES_3),
    MERCHANT_40(40 , "Mobile Shop" , "موبايل شوب","",MerchantCategories.MERCHANT_CATEGORIES_3),
    MERCHANT_41(41 , "Smart Homes" , "سمارت هومز","",MerchantCategories.MERCHANT_CATEGORIES_3),
    MERCHANT_42(42 , "B.Tech" , "بي تك","",MerchantCategories.MERCHANT_CATEGORIES_3),
    MERCHANT_43(43 , "Dubai Phone" , "دبي فون","",MerchantCategories.MERCHANT_CATEGORIES_3),
    MERCHANT_44(44 , "Lulu Market" , "لولو ماركت","",MerchantCategories.MERCHANT_CATEGORIES_4),
    MERCHANT_45(45 , "Kheir Zaman" , "خير زمان","",MerchantCategories.MERCHANT_CATEGORIES_4),
    MERCHANT_46(46 , "Fathallah Market" , "أسواق فتح الله","",MerchantCategories.MERCHANT_CATEGORIES_4),
    MERCHANT_47(47 , "Gomla Market" , "أسواق جملة","",MerchantCategories.MERCHANT_CATEGORIES_4),
    MERCHANT_48(48 , "Spinneys" , "سبينيس","",MerchantCategories.MERCHANT_CATEGORIES_4),
    MERCHANT_49(49 , "Damas" , "داماس","",MerchantCategories.MERCHANT_CATEGORIES_5),
    MERCHANT_50(50 , "C&CO" , "سي أند كو","",MerchantCategories.MERCHANT_CATEGORIES_5),
    MERCHANT_51(51 , "Monir Nassif Eyewear" , "نظارات منير نصيف","",MerchantCategories.MERCHANT_CATEGORIES_5),
    MERCHANT_52(52 , "Hedeya" , "هدية","",MerchantCategories.MERCHANT_CATEGORIES_5),
    MERCHANT_53(53 , "Hope flowers" , "زهور هوب","",MerchantCategories.MERCHANT_CATEGORIES_5),
    MERCHANT_54(54 , "Joly Optics" , "جولي للبصريات","",MerchantCategories.MERCHANT_CATEGORIES_5),
    MERCHANT_55(55 , "Baraka" , "بركة","",MerchantCategories.MERCHANT_CATEGORIES_5),
    MERCHANT_56(56 , "Blue Bus" , "بلو باص","",MerchantCategories.MERCHANT_CATEGORIES_6),
    MERCHANT_57(57 , "careem" , "كريم","",MerchantCategories.MERCHANT_CATEGORIES_6),
    MERCHANT_58(58 , "Bloom Pharmacies" , "صيدليات بلوم","",MerchantCategories.MERCHANT_CATEGORIES_7),
    MERCHANT_59(59 , "Inglot Cosmetics" , " انجلوت لمستحضرات التجميل","",MerchantCategories.MERCHANT_CATEGORIES_7),
    MERCHANT_60(60 , "Seif Pharmacies" , "صيدليات سيف","",MerchantCategories.MERCHANT_CATEGORIES_7),
    MERCHANT_61(61 , "Alfa Scan" , "الفا سكان","",MerchantCategories.MERCHANT_CATEGORIES_7),
    MERCHANT_62(62 , "El Mokhtabar" , "المختبر","",MerchantCategories.MERCHANT_CATEGORIES_7),
    MERCHANT_63(63 , "Bakier" , "بكير","",MerchantCategories.MERCHANT_CATEGORIES_8),
    MERCHANT_64(64 , "Samir & Aly" , "سمير وعلي","",MerchantCategories.MERCHANT_CATEGORIES_8),
    MERCHANT_65(65 , "Tulipe" , "تيوليب","",MerchantCategories.MERCHANT_CATEGORIES_9),
    MERCHANT_66(66 , "Omash" , "قماش","",MerchantCategories.MERCHANT_CATEGORIES_9),
    MERCHANT_67(67 , "Breadfast" , "بريدفاست","",MerchantCategories.MERCHANT_CATEGORIES_10),
    MERCHANT_68(67 , "On the run" , "أون ذا ران","",MerchantCategories.MERCHANT_CATEGORIES_11),
    MERCHANT_69(67 , "Ghataty" , "غطاطي","",MerchantCategories.MERCHANT_CATEGORIES_11),
    MERCHANT_70(67 , "Abaza Auto trade" , "أباظه أوتو تريد","",MerchantCategories.MERCHANT_CATEGORIES_11),
    MERCHANT_71(67 , "circle k" , "سيركل كي","",MerchantCategories.MERCHANT_CATEGORIES_11),
}