package com.example.firstapi.models.enums

enum class MerchantsLogos(
    val id: Int,
    val merchantsNameEn: String,
    val merchantsNameAr: String,
    val logoUrl: String,
    val categoriesId:Int,
    val categoriesNameAr:String,
    val categoriesNameEn:String
) {
    MERCHANT_1(1 , "M.SOU" , "إم-سو" , "",1,"ازياء","Fashion"),
    MERCHANT_2(2 , "LC Waikiki" , "إل سي وايكيكي","",1,"ازياء","Fashion"),
    MERCHANT_3(3 , "adidas kids" , "أديداس كيدز","",1,"ازياء","Fashion"),
    MERCHANT_4(4 , "pixi" , "بيكسي","",1,"ازياء","Fashion"),
    MERCHANT_5(5 , "NIKE" , "نايك","",1,"ازياء","Fashion"),
    MERCHANT_6(6 , "Calvin Klein" , "كالفن كلاين","",1,"ازياء","Fashion"),
    MERCHANT_7(7 , "Charles & Keith" , "تشارلز و كيث","",1,"ازياء","Fashion"),
    MERCHANT_8(8 , "Polo Ralph Lauren" , "بولو - رالف لورين","",1,"ازياء","Fashion"),
    MERCHANT_9(9 , "Hackett" , "هاكيت","",1,"ازياء","Fashion"),
    MERCHANT_10(10 , "Tommy Hilfiger" , "تومي هيلفيجر","",1,"ازياء","Fashion"),
    MERCHANT_11(11 , "Matalan" , "ماتالان","",1,"ازياء","Fashion"),
    MERCHANT_12(12 , "Ofive" , "أو قايف","",1,"ازياء","Fashion"),
    MERCHANT_13(13 , "New Balance" , "نيو بالانس","",1,"ازياء","Fashion"),
    MERCHANT_14(14 , "Dejavu" , "ديجافو","",1,"ازياء","Fashion"),
    MERCHANT_15(15 , "New Born" , "نيوبورن","",1,"ازياء","Fashion"),
    MERCHANT_16(16 , "Town Team" , "تاون تيم","",1,"ازياء","Fashion"),
    MERCHANT_17(17 , "Abou Shakra" , "ابو شقرة","",2,"المطاعم والكافيهات","Resturant & Cafe"),
    MERCHANT_18(18 , "Kazouza" , "كازوزه","",2,"المطاعم والكافيهات","Resturant & Cafe"),
    MERCHANT_19(19 , "Hajj Arafa" , "الحاج عرفة","",2,"المطاعم والكافيهات","Resturant & Cafe"),
    MERCHANT_20(20 , "TBS" , "تي بي اس","",2,"المطاعم والكافيهات","Resturant & Cafe"),
    MERCHANT_21(21 , "Carinos pizzeria" , "بيتزا كارينوس","",2,"المطاعم والكافيهات","Resturant & Cafe"),
    MERCHANT_22(22 , "Chili's" , "تشيليز","",2,"المطاعم والكافيهات","Resturant & Cafe"),
    MERCHANT_23(23 , "Kababgy Studio Masr" , "كبابجى ستوديو مصر","",2,"المطاعم والكافيهات","Resturant & Cafe"),
    MERCHANT_24(24 , "La Poire" , "لابوار","",2,"المطاعم والكافيهات","Resturant & Cafe"),
    MERCHANT_25(25 , "Beanos" , "بينوس","",2,"المطاعم والكافيهات","Resturant & Cafe"),
    MERCHANT_26(26 , "Halaket El Samak" , "حلقة السمك","",2,"المطاعم والكافيهات","Resturant & Cafe"),
    MERCHANT_27(27 , "La Poire café" , "مقهى لابوار","",2,"المطاعم والكافيهات","Resturant & Cafe"),
    MERCHANT_28(28 , "Mama's" , " مطعم ماما","",2,"المطاعم والكافيهات","Resturant & Cafe"),
    MERCHANT_29(29 , "Feteera" , "فطيرة","",2,"المطاعم والكافيهات","Resturant & Cafe"),
    MERCHANT_30(30 , "Coppermelt" , "كوبرميلت","",2,"المطاعم والكافيهات","Resturant & Cafe"),
    MERCHANT_31(31 , "Vinny's" , "فيني","",2,"المطاعم والكافيهات","Resturant & Cafe"),
    MERCHANT_32(32 , "Monginis" , "مونجيني","",2,"المطاعم والكافيهات","Resturant & Cafe"),
    MERCHANT_33(33 , "Vapiano" , "فابيانو","",2,"المطاعم والكافيهات","Resturant & Cafe"),
    MERCHANT_34(34 , "Tradeline" , "تريدلاين","",3,"الكترونيات","Electronics"),
    MERCHANT_35(35 , "CompuMe" , "كمبيومي","",3,"الكترونيات","Electronics"),
    MERCHANT_36(36 , "Virgin Megastore" , "فيرجن ميجاستور","",3,"الكترونيات","Electronics"),
    MERCHANT_37(37 , "RadioShack" , "راديو شاك","",3,"الكترونيات","Electronics"),
    MERCHANT_38(38 , "Switch Plus" , "سويتش بلس","",3,"الكترونيات","Electronics"),
    MERCHANT_39(39 , "Computer Shop" , "كمبيوتر شوب","",3,"الكترونيات","Electronics"),
    MERCHANT_40(40 , "Mobile Shop" , "موبايل شوب","",3,"الكترونيات","Electronics"),
    MERCHANT_41(41 , "Smart Homes" , "سمارت هومز","",3,"الكترونيات","Electronics"),
    MERCHANT_42(42 , "B.Tech" , "بي تك","",3,"الكترونيات","Electronics"),
    MERCHANT_43(43 , "Dubai Phone" , "دبي فون","",3,"الكترونيات","Electronics"),
    MERCHANT_44(44 , "Lulu Market" , "لولو ماركت","",4,"سوبر ماركت","Super Market"),
    MERCHANT_45(45 , "Kheir Zaman" , "خير زمان","",4,"سوبر ماركت","Super Market"),
    MERCHANT_46(46 , "Fathallah Market" , "أسواق فتح الله","",4,"سوبر ماركت","Super Market"),
    MERCHANT_47(47 , "Gomla Market" , "أسواق جملة","",4,"سوبر ماركت","Super Market"),
    MERCHANT_48(48 , "Spinneys" , "سبينيس","",4,"سوبر ماركت","Super Market"),
    MERCHANT_49(49 , "Damas" , "داماس","",5,"الاكسسوارات والمجوهرات","Accessories and jewelry"),
    MERCHANT_50(50 , "C&CO" , "سي أند كو","",5,"الاكسسوارات والمجوهرات","Accessories and jewelry"),
    MERCHANT_51(51 , "Monir Nassif Eyewear" , "نظارات منير نصيف","",5,"الاكسسوارات والمجوهرات","Accessories and jewelry"),
    MERCHANT_52(52 , "Hedeya" , "هدية","",5,"الاكسسوارات والمجوهرات","Accessories and jewelry"),
    MERCHANT_53(53 , "Hope flowers" , "زهور هوب","",5,"الاكسسوارات والمجوهرات","Accessories and jewelry"),
    MERCHANT_54(54 , "Joly Optics" , "جولي للبصريات","",5,"الاكسسوارات والمجوهرات","Accessories and jewelry"),
    MERCHANT_55(55 , "Baraka" , "بركة","",5,"الاكسسوارات والمجوهرات","Accessories and jewelry"),
    MERCHANT_56(56 , "Blue Bus" , "بلو باص","",6,"سفر","Travel"),
    MERCHANT_57(57 , "careem" , "كريم","",6,"سفر","Travel"),
    MERCHANT_58(58 , "Bloom Pharmacies" , "صيدليات بلوم","",7,"صحة وجمال","Health and Beauty"),
    MERCHANT_59(59 , "Inglot Cosmetics" , " انجلوت لمستحضرات التجميل","",7,"صحة وجمال","Health and Beauty"),
    MERCHANT_60(60 , "Seif Pharmacies" , "صيدليات سيف","",7,"صحة وجمال","Health and Beauty"),
    MERCHANT_61(61 , "Alfa Scan" , "الفا سكان","",7,"صحة وجمال","Health and Beauty"),
    MERCHANT_62(62 , "El Mokhtabar" , "المختبر","",7,"صحة وجمال","Health and Beauty"),
    MERCHANT_63(63 , "Bakier" , "بكير","",8,"مكتبات","Libraries"),
    MERCHANT_64(64 , "Samir & Aly" , "سمير وعلي","",8,"مكتبات","Libraries"),
    MERCHANT_65(65 , "Tulipe" , "تيوليب","",9,"الأثاث ","Furniture"),
    MERCHANT_66(66 , "Omash" , "قماش","",9,"الأثاث ","Furniture"),
    MERCHANT_67(67 , "Breadfast" , "بريدفاست","",10,"اونلاين ","Online"),
    MERCHANT_68(67 , "On the run" , "أون ذا ران","",11,"أخرى ","Other"),
    MERCHANT_69(67 , "Ghataty" , "غطاطي","",11,"أخرى ","Other"),
    MERCHANT_70(67 , "Abaza Auto trade" , "أباظه أوتو تريد","",11,"أخرى ","Other"),
    MERCHANT_71(67 , "circle k" , "سيركل كي","",11,"أخرى ","Other"),
}