package com.example.firstapi.util


/**
 * Main Error code for account service, handling English and Arabic error messages.
 *
 *
 * ACS -> Account Service
 * MWS -> Middleware Service
 * DBS -> Dashboard Service
 * PS -> Payment Service
 * CS -> Cards Service
 */
enum class ErrorCode(val code: String, val errorMessageEng: String, val errorMessageArb: String) {
    UNAUTHORIZED_ACCESS("401 UNAUTHORIZED", "Unauthorized access!", "Unauthorized access!"),
    CS_CORE_400("CS-CORE-400", "Please validate your request body", "يرجى التحقق من صحة نص الطلب الخاص بك"),
    CS_CORE_406("CS-CORE-406", "Please validate request parameters", "يرجى التحقق من صحة الطلب"),
    CS_CORE_407("CS-CORE-407", "Handler not found for requested method", "لم يتم العثور على المعالج للطريقة المطلوبة"),
    CS_CORE_408("CS-CORE-408", "Wrong exp. date , Please insert the correct exp. date", "يرجى التحقق من صحة تاريخ الانتهاء"),
    CS_CORE_999("CS-CORE-999", "Oops! Something went wrong", "هناك خطأ ما"),
    CS_CORE_404("CS-CORE-404", "No data found", "لاتوجد بيانات"),
    CS_BS_100("CS_BS_100", "Please select valid tenure", "من فضلك اختر مده صالحة"),
    CS_BS_101("CS_BS_101", "Please enter valid micro film reference number", "من فضلك ادخل رقم مرجعي صالح"),
    CS_MWS_TIMEOUT("CS-MWS-TIMEOUT", "Esb response timeouts", "مهلات استجابة Esb"),
    CS_CORE_405("CS-CORE-405", "No active account to fetch signature", "No active account to fetch signature  AR"),
    CS_CORE_401("CS-CORE-401", "Unauthorized Access!", "دخول غير مرخص!"),
    CS_INF_500("CS-INF-500", "Finacle Error response!", "استجابة خطأ"),
    ACS_CORE_400("ACS-CORE-400", "Please validate your request body", "يرجى التحقق من صحة نص الطلب الخاص بك"),
    ACS_CORE_406("ACS-CORE-406", "Request parameter is missing", "معلمة الطلب مفقودة"),
    ACS_CORE_407("ACS-CORE-407", "Handler not found for requested method", "لم يتم العثور على المعالج للطريقة المطلوبة"),
    ACS_CORE_999("ACS-CORE-999", "Something went wrong", "هناك خطأ ما"),
    ACS_CORE_404("ACS-CORE-404", "No data found", "لاتوجد بيانات"),
    ACS_INF_500("ACS-INF-500", "Finacle Error response!", "استجابة خطأ"),
    ACS_MWS_500("ACS-MWS-500", "Middleware Error response!", "استجابة خطأ"),
    ACS_MWS_TIMEOUT("ACS-MWS-TIMEOUT", "Esb response timeouts", "مهلات استجابة Esb"),
    ACS_CORE_405("ACS-CORE-405", "No active account to fetch signature", "No active account to fetch signature  AR"),
    ACS_CORE_401("ACS-CORE-401", "Unauthorized Access!", "دخول غير مرخص!"),
    ACS_CORE_402("ACS-CORE-402", "Queuing bookings exceeded for the day!", "Queuing bookings exceeded for the day!  AR"),
    ACS_CORE_001("ACS-CORE-001", "CD not eligible for redemption", "القرص المضغوط غير مؤهل للاسترداد"),
    ACS_CORE_002("ACS-CORE-002", "Invalid account number", "رقم حساب غير صحيح"),
    DBS_CORE_400("DBS-CORE-400", "Please validate your request body", "يرجى التحقق من صحة نص الطلب الخاص بك"),
    DBS_CORE_406("DBS-CORE-406", "Request parameter is missing", "معلمة الطلب مفقودة"),
    DBS_CORE_407("DBS-CORE-407", "Handler not found for requested method", "لم يتم العثور على المعالج للطريقة المطلوبة"),
    DBS_CORE_999("DBS-CORE-999", "Something went wrong", "هناك خطأ ما "),
    DBS_CORE_404("DBS-CORE-404", "No data found", "لاتوجد بيانات"),
    DBS_CORE_401("DBS-CORE-401", "Unauthorized Access!", "دخول غير مرخص!"),
    DBS_INF_500("DBS-INF-500", "Finacle Error response!", "استجابة خطأ"),
    DBS_MWS_TIMEOUT("DBS-MWS-TIMEOUT", "Esb response timeouts", "مهلات استجابة Esb"),
    DBS_CORE_405("DBS-CORE-405", "No active account to fetch signature", "No active account to fetch signature AR"),
    PS_CORE_400("PS-CORE-400", "Please validate your request body", "يرجى التحقق من صحة نص الطلب الخاص بك"),
    PS_CORE_406("PS-CORE-406", "Request parameter is missing", "معلمة الطلب مفقودة"),
    PS_CORE_407("PS-CORE-407", "Handler not found for requested method", "لم يتم العثور على المعالج للطريقة المطلوبة"),
    PS_CORE_408("PS_CORE_408", "You've passed your daily transactions limit", "لقد تجاوزت حد معاملاتك اليومية"),
    PS_CORE_409("PS_CORE_409", "You've passed your daily amount limit, remaining: ", "لقد تجاوزت حد المبلغ اليومي، المتبقي: "),
    PS_CORE_410("PS_CORE_410", "You've passed your monthly transactions limit", "لقد تجاوزت حد معاملاتك الشهرية"),
    PS_CORE_411("PS_CORE_411", "You've passed your monthly amount limit, remaining: ", "لقد تجاوزت حد المبلغ الشهري المتبقي: "),
    PS_CORE_999("PS-CORE-999", "Something went wrong", "هناك خطأ ما"),
    PS_CORE_404("PS-CORE-404", "No data found", "لاتوجد بيانات"),
    PS_CORE_401("PS-CORE-401", "Unauthorized Access!", "دخول غير مرخص!"),
    PS_INF_500("PS-INF-500", "Finacle Error response!", "استجابة خطأ"),
    //    PS_MW_500("PS-MW-500", "Middleware Error response!", "استجابة خطأ البرامج الوسيطة!"),
    PS_MWS_TIMEOUT("PS-MWS-TIMEOUT", "Esb response timeouts", "مهلات استجابة Esb"),
    PS_MW_500("PS-MW-500", "Middleware Error response!", "استجابة خطأ البرامج الوسيطة!"),
    PS_CORE_405("PS-CORE-405", "No active account to fetch signature", "No active account to fetch signature AR"),
    PS_CORE_412("PS-CORE-412", "Invalid Account Number", "رقم حساب غير صحيح"),
    PS_CORE_413("PS-CORE-413", "Invalid Branch Code", "الكود التعريفي للفرع غير صحيح"),
    PS_CORE_414("PS-CORE-414", "No Accounts Available At Caching, Please Go To Dashboard ", "لا يوجد ارقام حسابات, من فضلك اذهب الي الصفحه الرئيسية"),
    AUTH_CORE_999("AUTH-CORE-999", "Something went wrong", "هناك خطأ ما"),
    AUTH_CORE_401("AUTH-CORE-401", "Unauthorized Access!", "دخول غير مرخص!"),
    AUTH_CORE_402("AUTH-CORE-402", "Change password failed!", "Change password failed! AR"),
    AUTH_CORE_405("AUTH-CORE-405", "Login attempts exceeded!", "Login attempts exceeded! AR"),
    AUTH_FIN_001("AUTH-FIN-001", "National Id and Account validation failure!", "National Id and Account validation failure! AR"),
    AUTH_FIN_002("AUTH-FIN-002", "Invalid Pin entered!", "تم إدخال رقم التعريف الشخصي غير صالح!"),
    AUTH_FIN_003("AUTH-FIN-003", "Invalid Pin attempt exceeded!", "Invalid Pin attempt exceeded! AR"),
    AUTH_FIN_004("AUTH-FIN-004", "OTP/ Pin validation error!", "OTP/ Pin validation error! AR"),
    AUTH_FIN_005("AUTH-FIN-005", "Username validation error!", "Username validation error! AR"),
    AUTH_FIN_006("AUTH-FIN-006", "Create user error!", "Create user error! AR"),
    AUTH_FIN_007("AUTH-FIN-007", "Internet Banking not activated", "Internet Banking not activated AR"),
    AUTH_FIN_008("AUTH-FIN-008", "User not registered on vasco", "User not registered on vasco"),
    AUTH_FIN_009("AUTH-FIN-009", "User already registered!", "User already registered! AR"),
    AUTH_CORE_009("AUTH-CORE-009", "Device registration issue!", "مشكلة في تسجيل الجهاز!"),
    AUTH_CORE_010("AUTH-CORE-010", "Issue mapping user with the device!", "مشكلة في تعيين المستخدم مع الجهاز"),
    AUTH_CORE_011("AUTH-CORE-011", "Device registration issue! Please login using credentials.", "Device registration issue! Please login using credentials. AR"),
    AUTH_CORE_012("AUTH-CORE-012", "Biometrics already enabled for user in another device! Do you want to continue?", "مستشعر البصمة تم تفعيله على جهاز أخر ، هل تريد المتابعة؟"),
    AUTH_CORE_013("AUTH-CORE-013", "User registration error! Please try again later", "User registration error! Please try again later"),
    AUTH_CORE_014("AUTH-CORE-014", "OTP/ Pin validation attempts exceeded. Please try after sometime!", "OTP/ Pin validation attempts exceeded. Please try after sometime!"),
    AUTH_CORE_015("AUTH-CORE-015", "Please validate Account Number/ Card Number against National Id!", "Please validate Account Number/ Card Number against National Id!"),
    AUTH_CORE_016("AUTH-CORE-016", "OTP/ Pin authentication error! Attempts left :", "OTP/ Pin authentication error! Attempts left :"),
    AUTH_CORE_017("AUTH-CORE-017", "Please authenticate OTP/ Pin!", "Please authenticate OTP/ Pin!"),
    AUTH_CORE_019("AUTH-CORE-019", "Username validation error! Attempts left :", "Username validation error! Attempts left :"),
    AUTH_CORE_022("AUTH-CORE-022", "Error while validating vasco token!", "Error while validating vasco token!"),
    AUTH_CORE_023("AUTH-CORE-023", "Unable to validate app version!", "Unable to validate app version!"),
    AUTH_CORE_018("AUTH-CORE-018", "Username validation attempt exceeded. PLease try after sometime!", "Username validation attempt exceeded. PLease try after sometime!"),
    AUTH_CORE_400("AUTH-CORE-400", "Please validate your request body", "يرجى التحقق من صحة نص الطلب الخاص بك"),
    AUTH_CORE_406("AUTH-CORE-406", "Request parameter is missing", "معلمة الطلب مفقودة"),
    AUTH_CORE_407("AUTH-CORE-407", "Handler not found for requested method", "لم يتم العثور على المعالج للطريقة المطلوبة"),
    AUTH_FIN_CONNECTION_ISSUE("AUTH-FIN-CONNECTION-ISSUE", "Connection failure. Please try again later", "خطأ في الأتصال برحاء المحاولة مره أخرى"),
    AUTH_FIN_INCORRECT_CURR_PWD("AUTH_FIN_INCORRECT_CURR_PWD", "Current password is incorrect", "كلمه المرور الحاليه غير صحيحه"),
    AUTH_FIN_SAME_NEW_CURR_PWD_ERROR("AUTH_FIN_SAME_NEW_CURR_PWD_ERROR", "New password cannot be same as any of previous ones", "كلمة المرور الجديدة لا يجب ان تكون مثل اي كلمة مرور سابقة"),
    CUST_CORE_400("CUST-CORE-400", "Please validate your request body", "يرجى التحقق من صحة نص الطلب الخاص بك"),
    CUST_CORE_406("CUST-CORE-406", "Request parameter is missing", "معلمة الطلب مفقودة"),
    CUST_CORE_407("CUST-CORE-407", "Handler not found for requested method", "لم يتم العثور على المعالج للطريقة المطلوبة"),
    CUST_CORE_999("CUST-CORE-999", "Something went wrong", "هناك خطأ ما"),
    CUST_CORE_404("CUST-CORE-404", "No data found", "لاتوجد بيانات"),
    CUST_CORE_408("CUST-CORE-408", "Your account isn't available at this moment, Please call 19888 or visit the nearest branch", "الحسابات الخاصة بكم غير متاحة الأن، برجاء الأتصال ب 19888 أو زيارة أقرب فرع"),
    CUST_MWS_TIMEOUT("CUST-MWS-TIMEOUT", "Esb response timeouts", "مهلات استجابة Esb"),
    CUST_CORE_405("CUST-CORE-405", "No active account to fetch signature", "No active account to fetch signature AR"),
    CUST_CORE_401("CUST-CORE-401", "Unauthorized Access!", "دخول غير مرخص!"),
    UTS_MWS_500("UTS-MWS-500", "Fawry Error response!", "Fawry Error response! AR"),
    UTS_CORE_401("UTS-CORE-401", "Unauthorized Access!", "دخول غير مرخص!"),
    UTS_CORE_999("UTS-CORE-999", "Something went wrong", "هناك خطأ ما"),
    UTS_CORE_400("UTS-CORE-400", "Please validate your request body", "يرجى التحقق من صحة نص الطلب الخاص بك"),
    UTS_CORE_404("UTS-CORE-404", "No data found", "لاتوجد بيانات"),
    UTS_CORE_406("UTS-CORE-406", "Request parameter is missing", "معلمة الطلب مفقودة"),
    UTS_CORE_407("UTS-CORE-407", "Handler not found for requested method", "لم يتم العثور على المعالج للطريقة المطلوبة"),
    UTS_CORE_408("UTS_CORE_408", "You've passed your daily transactions limit", "لقد تجاوزت حد معاملاتك اليومية"),
    UTS_CORE_409("UTS_CORE_409", "You've passed your daily amount limit, remaining: ", "لقد تجاوزت حد المبلغ اليومي، المتبقي: "),
    UTS_CORE_410("UTS_CORE_410", "You've passed your monthly transactions limit", "لقد تجاوزت حد معاملاتك الشهرية"),
    UTS_CORE_411("UTS_CORE_411", "You've passed your monthly amount limit, remaining: ", "لقد تجاوزت حد المبلغ الشهري المتبقي: "),
    UTS_CORE_412("UTS_CORE_412", "Amount not on the allowed range !", "المبلغ ليس في النطاق المسموح به !"),
    UTS_CORE_413("UTS_CORE_413", "Please enter a valid phone No.", "برجاء ادخال رقم هاتف صحيح"),
    UTS_CORE_414("UTS-CORE-414", "You've reached the maximum number of allowed favourite payments ", "You've reached the maximum number of allowed favourite payments"),
    UTS_CORE_415("UTS-CORE-415", "You have exceeded the maximum allowed length for the Favourite’s name, please try to add another name.", "لقد تجاوزت الحد الأقصى للطول المسموح به لاسم المفضلة ، يرجى محاولة إضافة اسم آخر."),
    UTS_CORE_416("UTS-CORE-416", "Favourite's name already exists please enter another one", " اسم المفضلة موجود بالفعل الرجاء إدخال اسم آخر"),
    UTS_CORE_417("UTS-CORE-417", "This favourite payment already exists. You can find it in your favourite list", "هذا المدفعوعة  المفضلة موجودة بالفعل. يمكنك أن تجدها في قائمة المفضلة لديك"),
    UTS_CORE_418("UTS-CORE-418", "The name contains invalid characters. Please enter a different name.The following characters are not allowed ! @ # \$ % ^ & * ( ) + | } \" ? > < l ~Or any other special characters.",
        "الاسم يحتوي على أحرف خاطئة. الرجاء إدخال اسم مختلف.الأحرف التالية غير مسموح بها ! @ # \$٪ ^ & * () + | } \"؟> <l ~بالإضافة لأي رموز مميزة أخرى."),
    UTS_CORE_419("UTS-CORE-419", "Invalid biller account number!", "رقم حساب الفاتورة غير صحيح!"),
    UTS_INF_500("UTS-INF-500", "Finacle Error response!", "استجابة خطأ"),
    UTS_INF_501("UTS-INF-501", "Invalid reference number!", "الرقم المرجعي غير صحيح!"),
    ES_MWS_TIMEOUT("ES-MWS-TIMEOUT", "Esb response timeouts", "مهلات استجابة Esb"),
    ES_CORE_999("ES_CORE_999", "Something went wrong!", "هناك خطأ ما"),
    ES_CORE_400("ES-CORE-400", "Please validate your request body", "يرجى التحقق من صحة نص الطلب الخاص بك"),
    ES_CORE_415("ES_CORE_415", "media type not supported.", "media type not supported. AR"),
    ES_CORE_406("ES-CORE-406", "Request parameter is missing", "معلمة الطلب مفقودة"),
    ES_CORE_404("ES_CORE_404", "Handler not found.", "لم يتم العثور على المعالج للطريقة المطلوبة"),
    AUTH_CORE_408("AUTH-CORE-408", "Reset password general error ", "إعادة تعيين كلمة المرور خطأ عام"),
    AUTH_CORE_409("AUTH-CORE-409", "Registering with an account number is temporarily unavailable. Please try again with BM card number ", "التسجيل برقم الحساب غير متاح حالياً، الرجاء اعاده المحاوله بإستخدام رقم بطاقه بنك مصر"),
    UTS_MWS_501("UTS-MWS-501", "This service is temporarily unavailable ", "هذه الخدمه غير متاحه حالياً "),
    PS_CORE_402("PS_CORE_402", "Transfer to this beneficiary is temporarily unavailable. ", "التحويل الي هذا المستفيد غير متاح حالياً"),
    NS_CORE_999("NS-CORE-999", "Something went wrong", "هناك خطأ ما"),
    NS_CORE_400("NS-CORE-400", "Please validate your request body", "يرجى التحقق من صحة نص الطلب الخاص بك"),
    NS_CORE_406("NS-CORE-406", "Request parameter is missing", "معلمة الطلب مفقودة"),
    NS_CORE_401("NS-CORE-401", "Unauthorized Access!", "دخول غير مرخص!"),
    NS_CORE_407("NS-CORE-407", "Handler not found for requested method", "لم يتم العثور على المعالج للطريقة المطلوبة"),
    NS_MWS_TIMEOUT("NS-MWS-TIMEOUT", "Esb response timeouts", "مهلات استجابة Esb"),
    LS_MWS_TIMEOUT("LS-MWS-TIMEOUT", "Esb response timeouts", "مهلات استجابة Esb"),
    LS_CORE_001("LS-CORE-001", "sorry we can not offer you loan", "آسف لا يمكننا أن نقدم لك قرض"),
    LS_CORE_002("LS-CORE-002", "Application is already initiated", "بدأ التطبيق بالفعل"),
    LS_CORE_003("LS-CORE-003", "Please initiate application first", "الرجاء بدء التطبيق أولا"),
    LS_CORE_400("LS-CORE-400", "Please validate your request body", "يرجى التحقق من صحة نص الطلب الخاص بك"),
    LS_CORE_406("LS-CORE-406", "Please validate request parameters", "يرجى التحقق من صحة الطلب"),
    LS_CORE_407("LS-CORE-407", "Handler not found for requested method", "لم يتم العثور على المعالج للطريقة المطلوبة"),
    LS_CORE_999("LS-CORE-999", "Oops! Something went wrong", "هناك خطأ ما"),
    LS_CORE_DB("LS-CORE-DB", "Oops! Something went wrong", "هناك خطأ ما"),
    LS_DB_VERSION_ERROR("LS-DB-VERSION-ERROR", "Data is stale, please retry again", "البيانات قديمة ، يرجى إعادة المحاولة"),
    LS_CORE_500("LS-CORE-500", "Technical error occurred, please try after sometime", "حدث خطأ تقني ، يرجى المحاولة بعد وقت ما"),
    LS_CORE_TECH_500("LS-CORE-500", "Technical error occurred, please apply again", "حدث خطأ تقني ، يرجى تقديم الطلب مرة أخرى"),
    LS_VAL_401("LS-VAL-401", "Invalid National ID", "رقم قومي غير صحيح"),
    LS_VAL_402("LS-VAL-402", "Customer doesn't have active payroll card", "لاتوجد كارت مرتبات نشط"),
    LS_CORE_404("LS-CORE-404", "No data found", "لاتوجد بيانات"),
    LS_CORE_401("LS-CORE-401", "Unauthorized Access!", "دخول ;ير مرخص!"),
    CBE_CORE_401("CBE-CORE-401", "Unauthorized Access!", "دخول ;ير مرخص!"),
    CBE_CORE_400("CBE-CORE-400", "Please validate your request body", "يرجى التحقق من صحة نص الطلب الخاص بك"),
    CBE_CORE_999("CBE-CORE-999", "Oops! Something went wrong", "هناك خطأ ما"),
    CBE_CORE_406("CBE-CORE-406", "Please validate request parameters", "يرجى التحقق من صحة الطلب"),
    CBE_CORE_407("CBE-CORE-407", "Handler not found for requested method", "لم يتم العثور على المعالج للطريقة المطلوبة"),
    CBE_SVC_CORE_DB("CBE-SVC-CORE-DB", "Oops! Something went wrong", "هناك خطأ ما"),
    AUTH_CORE_800("AUTH_CORE_800", "You have made five invalid attempts. you can try again after 1 hour ", "لقد قمت بخمس محاولات غير سليمة. يمكنك المحاولة مرة أخرى بعد 1 ساعة"),
    //TEMP ERROR CODES FOR QUICK WIN
    AUTH_FIN_110001("AUTH-FIN-110001", "Sorry, you can’t login right now. Please try again later.", "لا يمكن تسجيل الدخول في الوقت الحالي برجاء معاودة المحاولة في وقت لاحق"),
    AUTH_FIN_111109("AUTH-FIN-111109", "Sorry, you can’t login right now. Please try again later.", "لا يمكن تسجيل الدخول في الوقت الحالي برجاء معاودة المحاولة في وقت لاحق"),
    AUTH_FIN_101649("AUTH-FIN-101649", "Sorry, you can’t login right now. Please try again later.", "لا يمكن تسجيل الدخول في الوقت الحالي برجاء معاودة المحاولة في وقت لاحق"),
    AUTH_FIN_290007("AUTH-FIN-290007", "Sorry, We are running a scheduled maintenance", "نأسف ، نقوم حالياً بعمل تحديث على النظام"),
    PS_FIN_290007("PS-FIN-290007", "Sorry, We are running a scheduled maintenance", "نأسف ، نقوم حالياً بعمل تحديث على النظام"),
    PAY_FIN_260112("PAY-FIN-260112", "The entered account number is already in your beneficiary list", "رقم الحساب المدخل موجود بالفعل في قائمة المستفيدين الخاصة بك"),
    // error code in stopping foreign currencies TDs in  minimum versions
    ACS_BE_400("ACS_BE_400", "Dear valued customer, please update to the latest App version to apply for a ‘time deposit’ with foreign currency.", "عميلنا العزيز، يرجى تحديث التطبيق إلى الإصدار الأحدث لكي تتمكن من شراء الودائع بالعملات الأجنبية"),
    OFS_CORE_400("OFS-CORE-400", "Please validate your request body", "يرجى التحقق من صحة نص الطلب الخاص بك"),
    OFS_CORE_404("OFS-CORE-404", "No data found", "لاتوجد بيانات"),
    OFS_CORE_406("OFS-CORE-406", "Request parameter is missing", "معلمة الطلب مفقودة"),
    OFS_CORE_407("OFS-CORE-407", "Handler not found for requested method", "لم يتم العثور على المعالج للطريقة المطلوبة"),
    OFS_CORE_408("OFS-CORE-408", "Please check logo specifications", ""),
    OFS_CORE_409("OFS-CORE-409", "Merchant already exist", ""),
    OFS_CORE_410("OFS-CORE-410", "Starting date must be before expiry date", ""),
    OFS_CORE_411("OFS-CORE-411", "Expiry date must be ahead of the Starting date", ""),
    OFS_CORE_412("OFS-CORE-412", "Starting date must be the same day or ahead of the Sys date", ""),
    OFS_CORE_413("OFS-CORE-413", "File is not found", "الملف غير موجود"),
    OFS_CORE_415("OFS-CORE-415", "Please Enter Store Location", ""),
    OFS_CORE_416("OFS-CORE-416", "Please Enter Merchant Website", ""),
    OFS_CORE_417("OFS-CORE-417", "Offer already pinned/ Not eligible", "العرض مثبت بالفعل / غير مؤهل"),
    OFS_CORE_418("OFS-CORE-418", "Data doesn't match the offer type", ""),
    OFS_CORE_419("OFS-CORE-419", "Question code is not found", "الكود التعريفي للسؤال غير موجود"),
    OFS_CORE_420("OFS-CORE-420", "Other feedback is mandatory", "الاسباب الاخرى إلزامية"),
    OFS_CORE_421("OFS-CORE-421", "Unuseful reason is mandatory", "أسباب عدم الرضا إلزامية"),
    OFS_CORE_422("OFS-CORE-422", "Minimum 5 characters required", "الحد الأدنى المطلوب 5 أحرف"),
    OFS_CORE_999("OFS-CORE-999", "Something went wrong", "هناك خطأ ما"),
    OFS_CORE_401("OFS-CORE-401", "Unauthorized Access!", "دخول غير مرخص!"),
    OFS_CORE_403("OFS-CORE-403", "Forbidden!", ""),
    OFS_CORE_423("OFS-CORE-423", "This Offer Saved as a Favourite for you before", "العرض موجود بالفعل في المفضله اليك"),
    OFS_CORE_424("OFS-CORE-424", "This Offer not Published", "هذا العرض غير متاح للعرض حاليا");
    companion object {
        private val map = ErrorCode.values().associateBy(ErrorCode::code)

        /**
         * Gets ErrorCode based on code string provided in the method parameter
         */
        fun fromCode(code: String): ErrorCode {
            return listOf(*values()).stream()
                .filter { errorCode: ErrorCode -> errorCode.code == code }
                .findFirst()
                .orElse(ACS_CORE_999)
        }

        fun msgFromCode(code: String, locale: String): String {
            return if (locale == "ar")
                (map[code] ?: error("")).errorMessageArb
            else
                (map[code] ?: error("")).errorMessageEng
        }
    }

}